slug: prodanovtsi-samokov
ekatte: '58548'
code: SFO39
locale:
  bg:
    name: Село Продановци (общ. Самоков)
    description: '...'
  en:
    name: Prodanovtsi Village (Samokov Municipality)
    description: '...'
