slug: prodanovtsi-veliko-tarnovo
ekatte: '58520'
code: VTR04
locale:
  bg:
    name: Село Продановци (общ. Велико Търново)
    description: '...'
  en:
    name: Prodanovtsi Village (Veliko Tarnovo Municipality)
    description: '...'
