slug: prodanovtsi-gabrovo
ekatte: '59300'
code: GAB05
locale:
  bg:
    name: Село Продановци (общ. Габрово)
    description: '...'
  en:
    name: Prodanovtsi Village (Gabrovo Municipality)
    description: '...'
